#spring:
#  application:
#    name: "Spring-security-basic"
#
#  security:
#    user:
#      name: "handsome"
#      password: 123456

server:
  port: 8080
spring:
  application:
    name: spring-security-basic
  datasource:
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring-security-db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop # or update
    generate-ddl: true

